In [1]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np 
import pandas as pd

plt.style.use("fivethirtyeight")

In [2]:
class Perceptron:
    
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) *1e-4
        self.eta = eta  # learning rate
        self.epochs = epochs  # iterations
        
    def _z_value(self, inputs, weights):
        return np.dot(inputs, weights) 
    
    def activation_function(self, z):
        return np.where(z>0, 1, 0)   #step function
        
    def fit(self, x, y):
        self.x = x
        self.y = y
        
        x_with_bias = np.c_[self.x, -np.ones((len(self.x), 1))]
        print(f"X with Bias : \n{x_with_bias}")
        
        for epoch in range(self.epochs):
            z = self._z_value(x_with_bias, self.weights)
            y_hat = self.activation_function(z)
            
            self.error = self.y - y_hat
        
            self.weights = self.weights + self.eta*np.dot(x_with_bias.T, self.error)
        
    def predict(self, x):
        x_with_bias = np.c_[x, -np.ones((len(x), 1))]
        z = self._z_value(x_with_bias, self.weights)
        return self.activation_function(z)

In [3]:
OR = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "y" : [0, 1, 1, 1]
}

df_OR = pd.DataFrame(OR)

In [4]:
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [5]:
def data_prep(df, target_col = "y"):
    x = df.drop(target_col, axis = 1)
    y = df[target_col]
    
    return x, y

In [6]:
x_inp, y_inp = data_prep(df_OR)

ETA = 0.1
EPOCHS = 10


model = Perceptron(eta=ETA, epochs=EPOCHS)

model.fit(x_inp, y_inp)

X with Bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]


In [7]:
model.predict(x_inp)

array([0, 1, 1, 1])

In [8]:
model.predict([[1,0]])

array([1])